[package]
name = "rider"
version = "0.1.0"
authors = ["yuukis"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

vulkano = { git = "https://github.com/vulkano-rs/vulkano.git" }